In [2]:
import pandas as pd
import torch
import sklearn

In [3]:
df = pd.read_csv("AWE_1000_score.csv")

In [4]:
df.head(2)

Unnamed: 0                     id nationality sex          title  \
0           1  A100000_v01.txt_2.txt          중국  남자  우리 나라의 계절과 날씨   
1           2  A100000_v02.txt_1.txt          중국  여자         주말 이야기   

                                             content  score  
0  제 나라의 계절은 아주 좋아요. 네 계절이 있습니다. 봄에는 날씨가 좋아요. 꽃이 ...     80  
1  어제 명동에 갔습니다. 친구하고 같이 갔습니다. 가게가 많습니다. 옷가게가 있었습니...     70

In [5]:
df["sentence"] = df["content"].apply(lambda x: len(x.split(".")))
#df["content"].apply(lambda x: len(x.split("."))).value_counts()

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = df["content"]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

array(['00', '00보터', '00시', ..., '힘들으지만', '힘들지', '힘들지만'], dtype=object)

In [16]:
len(vectorizer.get_feature_names_out())

8093

In [19]:
X

<1000x8093 sparse matrix of type '<class 'numpy.float64'>'
	with 34048 stored elements in Compressed Sparse Row format>

In [21]:
df["content_vector"] = X.todense().tolist()

In [22]:
df

Unnamed: 0                     id nationality sex          title  \
0             1  A100000_v01.txt_2.txt          중국  남자  우리 나라의 계절과 날씨   
1             2  A100000_v02.txt_1.txt          중국  여자         주말 이야기   
2             3  A100000_v03.txt_1.txt          중국  남자          여행 계획   
3             4  A100001_v01.txt_1.txt          중국  남자         주말 이야기   
4             5  A100001_v02.txt_1.txt          중국  남자         주말 이야기   
..          ...                    ...         ...  ..            ...   
995        1007  A200079_v01.txt_1.txt          일본  여자        사진기 빌리기   
996        1008  A200079_v01.txt_2.txt          일본  여자  우리 나라의 계절과 날씨   
997        1009  A200079_v02.txt_1.txt         스웨덴  남자             편지   
998        1010  A200079_v02.txt_2.txt         스웨덴  남자      기억에 남는 여행   
999        1011  A200080_v01.txt_1.txt          일본  여자        사진기 빌리기   

                                               content  score  sentence  \
0    제 나라의 계절은 아주 좋아요. 네 계절이 있습니다. 봄에는 날씨가 좋아요. 꽃이 ...     80        18   
1    어제 명동에 갔습니다. 친구하고 같이 갔습니다. 가게가 많습니다. 옷가게가 있었습니...     70        10   
2    저는 여행을 제주도에서 갈 싶습니다. 저는 친구 같이 갈 겁니다. 6월 15일 갈 ...     50         7   
3    주말에 도서관에서 공부했어요. 친구하고 노래방에서 노래했어요. 친구하고 식당에서 비...     60         9   
4     어제 저는 학교에 갔습니다. 학교에서 친구하고를 다닙니다. 학교에 학생 식당 있습니다.     20         4   
..                                                 ...    ...       ...   
995  하지만 빌리 씨는 사진기를 없었습니다. 그래서 빌리 씨는 아노코 씨에게 이야기하고 ...     90         7   
996  내 나라는 일본입니다. 일본의 계절은 뚜렷합니다. 봄은 다뜻합니다. 꽃을 많이 피나...     80        15   
997  잘 지냈어요? 저도 잘 지냈어요. 한국 생활은 아주 재미있고 편해요. 한국어 공부를...     80        11   
998  지난 주말에 친구들하고 이탈리아에서 축구 경기를 보러 갔습니다. 우리는 영국에서 비...     90        14   
999  하지만 빌리 씨는 사진기가 없었어요. 그 이야기를 나오코씨에게 이야기했어요. 그래서...     70         9   

                                        content_vector  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
995  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
996  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
997  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
998  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1549718154414...  
999  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[1000 rows x 9 columns]

In [ ]:
x_train = df["sentence"].to_numpy()
y_train = df["score"].to_numpy()

In [ ]:
x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)

In [ ]:
optimizer = torch.optim.SGD(params=[W], lr=0.1)

In [ ]:
# 데이터
#x_train = torch.FloatTensor([[1], [2], [3]]) 
#y_train = torch.FloatTensor([[1], [2], [3]]) # 모델 초기화
W = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W], lr=0.15)
nb_epochs = 10
for epoch in range(nb_epochs + 1):
# H(x) 계산
  hypothesis = x_train * W
  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)
  print('Epoch {:4d}/{} W: {:.3f} Cost: {:.6f}'.format( epoch, nb_epochs, W.item(), cost.item()
  ))
  # cost로 H(x) 개선 
  optimizer.zero_grad() 
  cost.backward() 
  optimizer.step()

Epoch    0/10 W: 0.000 Cost: 5608.200195
Epoch    1/10 W: 233.823 Cost: 6322896.000000
Epoch    2/10 W: -8105.219 Cost: 8041370624.000000
Epoch    3/10 W: 289297.594 Cost: 10227932987392.000000
Epoch    4/10 W: -10317248.000 Cost: 13009052212658176.000000
Epoch    5/10 W: 367953568.000 Cost: 16546398753796390912.000000
Epoch    6/10 W: -13122661376.000 Cost: 21045598030079411093504.000000
Epoch    7/10 W: 468005355520.000 Cost: 26768194840882427889451008.000000
Epoch    8/10 W: -16690897223680.000 Cost: 34046836186812315357893623808.000000
Epoch    9/10 W: 595262468784128.000 Cost: 43304636806515645697631302189056.000000
Epoch   10/10 W: -21229383394000896.000 Cost: 55079780058408038826072024817860608.000000


### 왜 loss가 발산할까?
 - lr이 너무 높아서
 - sample이 너무 많아서 loss값이 애초에 크다
 

In [ ]:
class MyLinearModel(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = torch.nn.Linear(in_features=2, out_features= 1)

  def forward(self, x):
    return self.linear(x)

In [ ]:
myLin = MyLinearModel()

In [ ]:
dummy_x_train = torch.FloatTensor([[2,5],[3,7],[4,9]])
dummy_y_train = torch.FloatTensor([[2],[3],[4]])

In [ ]:
list(myLin.parameters())

[Parameter containing:
 tensor([[0.7250, 0.0720]], requires_grad=True), Parameter containing:
 tensor([0.3461], requires_grad=True)]

In [ ]:
optimizer = torch.optim.SGD(myLin.parameters(), lr=0.01)

In [ ]:
myLin(dummy_x_train)

tensor([[-0.2273],
        [-0.3272],
        [-0.4271]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F

In [ ]:
# 데이터
x_train = dummy_x_train
y_train = dummy_y_train

nb_epochs = 10
for epoch in range(nb_epochs + 1):
# H(x) 계산
  hypothesis = myLin(x_train)
  # cost 계산
  cost = F.mse_loss(hypothesis, y_train)
  print('Epoch {:4d}/{} Cost: {:.6f}'.format( epoch, nb_epochs, cost.item()
  ))
  # cost로 H(x) 개선 
  optimizer.zero_grad() 
  cost.backward() 
  optimizer.step()

Epoch    0/10 W: 757122676094402560.000 Cost: 11.876952
Epoch    1/10 W: 757122676094402560.000 Cost: 0.726773
Epoch    2/10 W: 757122676094402560.000 Cost: 0.055365
Epoch    3/10 W: 757122676094402560.000 Cost: 0.014908
Epoch    4/10 W: 757122676094402560.000 Cost: 0.012442
Epoch    5/10 W: 757122676094402560.000 Cost: 0.012264
Epoch    6/10 W: 757122676094402560.000 Cost: 0.012224
Epoch    7/10 W: 757122676094402560.000 Cost: 0.012192
Epoch    8/10 W: 757122676094402560.000 Cost: 0.012161
Epoch    9/10 W: 757122676094402560.000 Cost: 0.012129
Epoch   10/10 W: 757122676094402560.000 Cost: 0.012098
